services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/app
      ACCESS_TOKEN_SECRET: e5482cabc11524e32e29a8436a18f4bc7da48399b778a58eb9f1e4236959b6b3
      REFRESH_TOKEN_SECRET: 36824f3f7f4c9d548be522f4f0f057b413d04cbbe801929055207dde1ddbe8ed
    ports:
      - "3550:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: